/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThoughtsRouteImport } from './routes/thoughts'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as MemoriesRouteImport } from './routes/memories'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostSlugRouteImport } from './routes/post.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as EnPostSlugRouteImport } from './routes/en.post.$slug'
import { Route as BnPostSlugRouteImport } from './routes/bn.post.$slug'
import { Route as AuthenticatedAdminTestimonialsRouteImport } from './routes/_authenticated/admin.testimonials'
import { Route as AuthenticatedAdminSkillsRouteImport } from './routes/_authenticated/admin.skills'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminServicesRouteImport } from './routes/_authenticated/admin.services'
import { Route as AuthenticatedAdminQuotesRouteImport } from './routes/_authenticated/admin.quotes'
import { Route as AuthenticatedAdminProjectsRouteImport } from './routes/_authenticated/admin.projects'
import { Route as AuthenticatedAdminPostsRouteImport } from './routes/_authenticated/admin.posts'
import { Route as AuthenticatedAdminPeopleRouteImport } from './routes/_authenticated/admin.people'
import { Route as AuthenticatedAdminMessagesRouteImport } from './routes/_authenticated/admin.messages'
import { Route as AuthenticatedAdminMemoriesRouteImport } from './routes/_authenticated/admin.memories'
import { Route as AuthenticatedAdminHobbiesRouteImport } from './routes/_authenticated/admin.hobbies'
import { Route as AuthenticatedAdminEducationRouteImport } from './routes/_authenticated/admin.education'
import { Route as AuthenticatedAdminContactRouteImport } from './routes/_authenticated/admin.contact'
import { Route as AuthenticatedAdminCertificatesRouteImport } from './routes/_authenticated/admin.certificates'

const ThoughtsRoute = ThoughtsRouteImport.update({
  id: '/thoughts',
  path: '/thoughts',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriesRoute = MemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostSlugRoute = PostSlugRouteImport.update({
  id: '/post/$slug',
  path: '/post/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const EnPostSlugRoute = EnPostSlugRouteImport.update({
  id: '/en/post/$slug',
  path: '/en/post/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BnPostSlugRoute = BnPostSlugRouteImport.update({
  id: '/bn/post/$slug',
  path: '/bn/post/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminTestimonialsRoute =
  AuthenticatedAdminTestimonialsRouteImport.update({
    id: '/admin/testimonials',
    path: '/admin/testimonials',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSkillsRoute =
  AuthenticatedAdminSkillsRouteImport.update({
    id: '/admin/skills',
    path: '/admin/skills',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminServicesRoute =
  AuthenticatedAdminServicesRouteImport.update({
    id: '/admin/services',
    path: '/admin/services',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminQuotesRoute =
  AuthenticatedAdminQuotesRouteImport.update({
    id: '/admin/quotes',
    path: '/admin/quotes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminProjectsRoute =
  AuthenticatedAdminProjectsRouteImport.update({
    id: '/admin/projects',
    path: '/admin/projects',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPostsRoute = AuthenticatedAdminPostsRouteImport.update({
  id: '/admin/posts',
  path: '/admin/posts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminPeopleRoute =
  AuthenticatedAdminPeopleRouteImport.update({
    id: '/admin/people',
    path: '/admin/people',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminMessagesRoute =
  AuthenticatedAdminMessagesRouteImport.update({
    id: '/admin/messages',
    path: '/admin/messages',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminMemoriesRoute =
  AuthenticatedAdminMemoriesRouteImport.update({
    id: '/admin/memories',
    path: '/admin/memories',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminHobbiesRoute =
  AuthenticatedAdminHobbiesRouteImport.update({
    id: '/admin/hobbies',
    path: '/admin/hobbies',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminEducationRoute =
  AuthenticatedAdminEducationRouteImport.update({
    id: '/admin/education',
    path: '/admin/education',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminContactRoute =
  AuthenticatedAdminContactRouteImport.update({
    id: '/admin/contact',
    path: '/admin/contact',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCertificatesRoute =
  AuthenticatedAdminCertificatesRouteImport.update({
    id: '/admin/certificates',
    path: '/admin/certificates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/journey': typeof JourneyRoute
  '/memories': typeof MemoriesRoute
  '/people': typeof PeopleRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/thoughts': typeof ThoughtsRoute
  '/post/$slug': typeof PostSlugRoute
  '/admin/certificates': typeof AuthenticatedAdminCertificatesRoute
  '/admin/contact': typeof AuthenticatedAdminContactRoute
  '/admin/education': typeof AuthenticatedAdminEducationRoute
  '/admin/hobbies': typeof AuthenticatedAdminHobbiesRoute
  '/admin/memories': typeof AuthenticatedAdminMemoriesRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/admin/people': typeof AuthenticatedAdminPeopleRoute
  '/admin/posts': typeof AuthenticatedAdminPostsRoute
  '/admin/projects': typeof AuthenticatedAdminProjectsRoute
  '/admin/quotes': typeof AuthenticatedAdminQuotesRoute
  '/admin/services': typeof AuthenticatedAdminServicesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/skills': typeof AuthenticatedAdminSkillsRoute
  '/admin/testimonials': typeof AuthenticatedAdminTestimonialsRoute
  '/bn/post/$slug': typeof BnPostSlugRoute
  '/en/post/$slug': typeof EnPostSlugRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/journey': typeof JourneyRoute
  '/memories': typeof MemoriesRoute
  '/people': typeof PeopleRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/thoughts': typeof ThoughtsRoute
  '/post/$slug': typeof PostSlugRoute
  '/admin/certificates': typeof AuthenticatedAdminCertificatesRoute
  '/admin/contact': typeof AuthenticatedAdminContactRoute
  '/admin/education': typeof AuthenticatedAdminEducationRoute
  '/admin/hobbies': typeof AuthenticatedAdminHobbiesRoute
  '/admin/memories': typeof AuthenticatedAdminMemoriesRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/admin/people': typeof AuthenticatedAdminPeopleRoute
  '/admin/posts': typeof AuthenticatedAdminPostsRoute
  '/admin/projects': typeof AuthenticatedAdminProjectsRoute
  '/admin/quotes': typeof AuthenticatedAdminQuotesRoute
  '/admin/services': typeof AuthenticatedAdminServicesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/skills': typeof AuthenticatedAdminSkillsRoute
  '/admin/testimonials': typeof AuthenticatedAdminTestimonialsRoute
  '/bn/post/$slug': typeof BnPostSlugRoute
  '/en/post/$slug': typeof EnPostSlugRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/journey': typeof JourneyRoute
  '/memories': typeof MemoriesRoute
  '/people': typeof PeopleRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/thoughts': typeof ThoughtsRoute
  '/post/$slug': typeof PostSlugRoute
  '/_authenticated/admin/certificates': typeof AuthenticatedAdminCertificatesRoute
  '/_authenticated/admin/contact': typeof AuthenticatedAdminContactRoute
  '/_authenticated/admin/education': typeof AuthenticatedAdminEducationRoute
  '/_authenticated/admin/hobbies': typeof AuthenticatedAdminHobbiesRoute
  '/_authenticated/admin/memories': typeof AuthenticatedAdminMemoriesRoute
  '/_authenticated/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/_authenticated/admin/people': typeof AuthenticatedAdminPeopleRoute
  '/_authenticated/admin/posts': typeof AuthenticatedAdminPostsRoute
  '/_authenticated/admin/projects': typeof AuthenticatedAdminProjectsRoute
  '/_authenticated/admin/quotes': typeof AuthenticatedAdminQuotesRoute
  '/_authenticated/admin/services': typeof AuthenticatedAdminServicesRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/skills': typeof AuthenticatedAdminSkillsRoute
  '/_authenticated/admin/testimonials': typeof AuthenticatedAdminTestimonialsRoute
  '/bn/post/$slug': typeof BnPostSlugRoute
  '/en/post/$slug': typeof EnPostSlugRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contact'
    | '/journey'
    | '/memories'
    | '/people'
    | '/sitemap.xml'
    | '/thoughts'
    | '/post/$slug'
    | '/admin/certificates'
    | '/admin/contact'
    | '/admin/education'
    | '/admin/hobbies'
    | '/admin/memories'
    | '/admin/messages'
    | '/admin/people'
    | '/admin/posts'
    | '/admin/projects'
    | '/admin/quotes'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/skills'
    | '/admin/testimonials'
    | '/bn/post/$slug'
    | '/en/post/$slug'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contact'
    | '/journey'
    | '/memories'
    | '/people'
    | '/sitemap.xml'
    | '/thoughts'
    | '/post/$slug'
    | '/admin/certificates'
    | '/admin/contact'
    | '/admin/education'
    | '/admin/hobbies'
    | '/admin/memories'
    | '/admin/messages'
    | '/admin/people'
    | '/admin/posts'
    | '/admin/projects'
    | '/admin/quotes'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/skills'
    | '/admin/testimonials'
    | '/bn/post/$slug'
    | '/en/post/$slug'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/contact'
    | '/journey'
    | '/memories'
    | '/people'
    | '/sitemap.xml'
    | '/thoughts'
    | '/post/$slug'
    | '/_authenticated/admin/certificates'
    | '/_authenticated/admin/contact'
    | '/_authenticated/admin/education'
    | '/_authenticated/admin/hobbies'
    | '/_authenticated/admin/memories'
    | '/_authenticated/admin/messages'
    | '/_authenticated/admin/people'
    | '/_authenticated/admin/posts'
    | '/_authenticated/admin/projects'
    | '/_authenticated/admin/quotes'
    | '/_authenticated/admin/services'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/skills'
    | '/_authenticated/admin/testimonials'
    | '/bn/post/$slug'
    | '/en/post/$slug'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  JourneyRoute: typeof JourneyRoute
  MemoriesRoute: typeof MemoriesRoute
  PeopleRoute: typeof PeopleRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ThoughtsRoute: typeof ThoughtsRoute
  PostSlugRoute: typeof PostSlugRoute
  BnPostSlugRoute: typeof BnPostSlugRoute
  EnPostSlugRoute: typeof EnPostSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thoughts': {
      id: '/thoughts'
      path: '/thoughts'
      fullPath: '/thoughts'
      preLoaderRoute: typeof ThoughtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memories': {
      id: '/memories'
      path: '/memories'
      fullPath: '/memories'
      preLoaderRoute: typeof MemoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/$slug': {
      id: '/post/$slug'
      path: '/post/$slug'
      fullPath: '/post/$slug'
      preLoaderRoute: typeof PostSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/en/post/$slug': {
      id: '/en/post/$slug'
      path: '/en/post/$slug'
      fullPath: '/en/post/$slug'
      preLoaderRoute: typeof EnPostSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bn/post/$slug': {
      id: '/bn/post/$slug'
      path: '/bn/post/$slug'
      fullPath: '/bn/post/$slug'
      preLoaderRoute: typeof BnPostSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/testimonials': {
      id: '/_authenticated/admin/testimonials'
      path: '/admin/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AuthenticatedAdminTestimonialsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/skills': {
      id: '/_authenticated/admin/skills'
      path: '/admin/skills'
      fullPath: '/admin/skills'
      preLoaderRoute: typeof AuthenticatedAdminSkillsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/services': {
      id: '/_authenticated/admin/services'
      path: '/admin/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AuthenticatedAdminServicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/quotes': {
      id: '/_authenticated/admin/quotes'
      path: '/admin/quotes'
      fullPath: '/admin/quotes'
      preLoaderRoute: typeof AuthenticatedAdminQuotesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/projects': {
      id: '/_authenticated/admin/projects'
      path: '/admin/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AuthenticatedAdminProjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/posts': {
      id: '/_authenticated/admin/posts'
      path: '/admin/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AuthenticatedAdminPostsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/people': {
      id: '/_authenticated/admin/people'
      path: '/admin/people'
      fullPath: '/admin/people'
      preLoaderRoute: typeof AuthenticatedAdminPeopleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/messages': {
      id: '/_authenticated/admin/messages'
      path: '/admin/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AuthenticatedAdminMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/memories': {
      id: '/_authenticated/admin/memories'
      path: '/admin/memories'
      fullPath: '/admin/memories'
      preLoaderRoute: typeof AuthenticatedAdminMemoriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/hobbies': {
      id: '/_authenticated/admin/hobbies'
      path: '/admin/hobbies'
      fullPath: '/admin/hobbies'
      preLoaderRoute: typeof AuthenticatedAdminHobbiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/education': {
      id: '/_authenticated/admin/education'
      path: '/admin/education'
      fullPath: '/admin/education'
      preLoaderRoute: typeof AuthenticatedAdminEducationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/contact': {
      id: '/_authenticated/admin/contact'
      path: '/admin/contact'
      fullPath: '/admin/contact'
      preLoaderRoute: typeof AuthenticatedAdminContactRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/certificates': {
      id: '/_authenticated/admin/certificates'
      path: '/admin/certificates'
      fullPath: '/admin/certificates'
      preLoaderRoute: typeof AuthenticatedAdminCertificatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminCertificatesRoute: typeof AuthenticatedAdminCertificatesRoute
  AuthenticatedAdminContactRoute: typeof AuthenticatedAdminContactRoute
  AuthenticatedAdminEducationRoute: typeof AuthenticatedAdminEducationRoute
  AuthenticatedAdminHobbiesRoute: typeof AuthenticatedAdminHobbiesRoute
  AuthenticatedAdminMemoriesRoute: typeof AuthenticatedAdminMemoriesRoute
  AuthenticatedAdminMessagesRoute: typeof AuthenticatedAdminMessagesRoute
  AuthenticatedAdminPeopleRoute: typeof AuthenticatedAdminPeopleRoute
  AuthenticatedAdminPostsRoute: typeof AuthenticatedAdminPostsRoute
  AuthenticatedAdminProjectsRoute: typeof AuthenticatedAdminProjectsRoute
  AuthenticatedAdminQuotesRoute: typeof AuthenticatedAdminQuotesRoute
  AuthenticatedAdminServicesRoute: typeof AuthenticatedAdminServicesRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminSkillsRoute: typeof AuthenticatedAdminSkillsRoute
  AuthenticatedAdminTestimonialsRoute: typeof AuthenticatedAdminTestimonialsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminCertificatesRoute: AuthenticatedAdminCertificatesRoute,
  AuthenticatedAdminContactRoute: AuthenticatedAdminContactRoute,
  AuthenticatedAdminEducationRoute: AuthenticatedAdminEducationRoute,
  AuthenticatedAdminHobbiesRoute: AuthenticatedAdminHobbiesRoute,
  AuthenticatedAdminMemoriesRoute: AuthenticatedAdminMemoriesRoute,
  AuthenticatedAdminMessagesRoute: AuthenticatedAdminMessagesRoute,
  AuthenticatedAdminPeopleRoute: AuthenticatedAdminPeopleRoute,
  AuthenticatedAdminPostsRoute: AuthenticatedAdminPostsRoute,
  AuthenticatedAdminProjectsRoute: AuthenticatedAdminProjectsRoute,
  AuthenticatedAdminQuotesRoute: AuthenticatedAdminQuotesRoute,
  AuthenticatedAdminServicesRoute: AuthenticatedAdminServicesRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminSkillsRoute: AuthenticatedAdminSkillsRoute,
  AuthenticatedAdminTestimonialsRoute: AuthenticatedAdminTestimonialsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  JourneyRoute: JourneyRoute,
  MemoriesRoute: MemoriesRoute,
  PeopleRoute: PeopleRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ThoughtsRoute: ThoughtsRoute,
  PostSlugRoute: PostSlugRoute,
  BnPostSlugRoute: BnPostSlugRoute,
  EnPostSlugRoute: EnPostSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
